# Generated by Django 5.2.4 on 2025-08-24 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_productview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
