version: '3.8'

services:
  backend:
    build: ./server
    container_name: django_app
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./server:/app
    expose:
      - "8000"

  frontend:
    build: ./client
    container_name: react_app
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
