version: '3.8'

services:
  backend:
    build: ./server
    container_name: django_app
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./server:/app
    expose:
      - "8000"

  frontend:
    build: ./client
    container_name: react_app
    ports:
      - "80:80" # 외부에서 React 접속 가능
    depends_on:
      - backend
