version: '3.8'

services:
  backend:
    build: ./server
    container_name: django_app
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./server:/app
      - ./media:/app/media
    expose:
      - "8000"

  frontend:
    build: ./client
    container_name: react_app
    ports:
      - "80:80" # 외부에서 React 접속 가능
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf   # nginx 설정 덮어쓰기
    depends_on:
      - backend
