export const PRODUCT_REVIEW_LIST_REQUEST = 'PRODUCT_REVIEW_LIST_REQUEST'
export const PRODUCT_REVIEW_LIST_SUCCESS = 'PRODUCT_REVIEW_LIST_SUCCESS'
export const PRODUCT_REVIEW_LIST_FAIL = 'PRODUCT_REVIEW_LIST_FAIL'
