// 리뷰 목록 조회
export const PRODUCT_REVIEW_LIST_REQUEST = 'PRODUCT_REVIEW_LIST_REQUEST'
export const PRODUCT_REVIEW_LIST_SUCCESS = 'PRODUCT_REVIEW_LIST_SUCCESS'
export const PRODUCT_REVIEW_LIST_FAIL = 'PRODUCT_REVIEW_LIST_FAIL'

// 리뷰 삭제
export const PRODUCT_REVIEW_DELETE_REQUEST = 'PRODUCT_REVIEW_DELETE_REQUEST'
export const PRODUCT_REVIEW_DELETE_SUCCESS = 'PRODUCT_REVIEW_DELETE_SUCCESS'
export const PRODUCT_REVIEW_DELETE_FAIL = 'PRODUCT_REVIEW_DELETE_FAIL'
export const PRODUCT_REVIEW_DELETE_RESET = 'PRODUCT_REVIEW_DELETE_RESET'

// 리뷰 수정
export const PRODUCT_REVIEW_UPDATE_REQUEST = 'PRODUCT_REVIEW_UPDATE_REQUEST'
export const PRODUCT_REVIEW_UPDATE_SUCCESS = 'PRODUCT_REVIEW_UPDATE_SUCCESS'
export const PRODUCT_REVIEW_UPDATE_FAIL = 'PRODUCT_REVIEW_UPDATE_FAIL'
export const PRODUCT_REVIEW_UPDATE_RESET = 'PRODUCT_REVIEW_UPDATE_RESET'